### ISSUE TITLE
decode json response

### ISSUE THREAD

**Issue by ripples-alive** [WordPress/Requests#167]
In the excellent Requests Python library, we can simply use the method `.json` to get the json decoded result. However, I can not do that with this library. Why not implement this?

**Comment by 73sl4** [comment]
@rmccue It can be done using the `Content-Type` header.
Can I work on it and generate a pull request?

**Comment by rmccue** [comment]
@73sl4 Absolutely! We should have a different method in `Requests_Response` for it, to match the Python one :)

**Comment by 73sl4** [comment]
@rmccue Please verify the PR.

**Comment by angelxmoreno** [comment]
status ?
