### ISSUE TITLE
Class 'Requests_Hooks' not found

### ISSUE THREAD

**Issue by andreabisello** [WordPress/Requests#304]
hi,
i downloaded the library with Composer
![image](https://user-images.githubusercontent.com/2149815/34304795-7efad82e-e73b-11e7-84fd-fc927e141ef9.png)
i uploaded only the library folder in my hosting
![image](https://user-images.githubusercontent.com/2149815/34304837-bad6eca2-e73b-11e7-9e34-4f86e2a9fa5e.png)
now, in a php file, same level of the lib_request folder,
i'm requiring
require_once 'lib_request/Requests.php'; 
but using, i obtain
[22-Dec-2017 17:17:01 Europe/Rome] PHP Fatal error:  Class 'Requests_Hooks' not found in /lib_request/Requests.php on line 568

any suggestion?

thanks.

**Comment by ExtinctAmoeba** [comment]
Any update/suggestion on this? I'm getting same error. 

After including with **_vendor/autoloader.php -> Requests.php_** getting same error. I tried to use Requests::register_autoloader(); but without success. Maybe I'm using wrong **"Requests::register_autoloader();"** ?

**Comment by jrfnl** [comment]
@andreabisello @ExtinctAmoeba The autoloading for Requests has been changed for Requests 2.0.0.

If you have the chance, it would be great if you would be able to test the current `develop` version of Requests to see if the problem has been fixed.

Upgrading instructions can be found here: https://github.com/WordPress/Requests/blob/develop/docs/upgrading.md

**Comment by jrfnl** [comment]
I'm going to close this issue now Requests 2.0.0 has been released. The autoloading has been changed in Requests 2.0.0, so this issue should be considered superseded.

If you still see issues with autoloading when using Requests 2.0.0, please open a new issue.
