### ISSUE TITLE
Question: Are there near-term plans for PSR-7 Message Interface compatibility?

### ISSUE THREAD

**Issue by skyzyx** [WordPress/Requests#320]
Are there near-term plans for PSR-7 Message Interface compatibility?

I'm developing some new software which leverages PSR-7 pretty heavily, and I'm wanting to write some tutorials for how to use it alongside Guzzle, Buzz, and Requests.

I know that Requests pre-dates PSR-7 by many years, but I didn't know if you had plans for a PSR-7 update.

**Comment by rmccue** [comment]
There's not really any near-term plans generally, as this project isn't on the front of my mind, but I do want to add PSR-7 some day. I had started work on a compatibility layer, and it was definitely possible, but we're missing the file streaming support which IIRC we need.

If you're interested in contributing to or helping maintain Requests, I could always use help. 😉

**Comment by mediaformat** [comment]
Bumping this in light of the recent v2 release

**Comment by jrfnl** [comment]
@mediaformat ;-)

First focus was to work through the technical debt which had build up over the years. Next focus is bug fixes and new features. 

Let's discuss this and we'd be happy to consider PRs, though in this case, a discussion on how to implement it first would probably be best.

**Comment by Art4** [comment]
Is there interest in being able to use the library as a PSR-18 HTTP client? The basis for this would be a PSR-7 implementation and I would be interested in helping with this.

The background is that I am helping to refactor SimplePie and plan to deprecate the SimplePie_File class and allow the usage of PSR-18 HTTP client and PSR-17 RequestFactory.

**Comment by jrfnl** [comment]
@Art4 In my opinion that would be a useful addition. We have semi-regular maintainer calls/working sessions. I'll put it on the agenda to discuss in the next one (and you'd be welcome to join the call if you'd like to discuss it in person).

**Comment by Art4** [comment]
Thanks for the invitation, but I'm afraid my work schedule won't allow me to have an in-person call.

My biggest question to start with a first draft is how and where to put the PSR interfaces, because I suspect that a new non-dev dependency is not allowed in `composer.json`?

**Comment by Art4** [comment]
I was wondering if anyone could take a look at #768? I'm not quite done yet, but wanted to know if the direction is right.
