### ISSUE TITLE
Drop support for old PHP versions

### ISSUE THREAD

**Issue by datagutten** [WordPress/Requests#378]
This project currently supports PHP versions down to 5.2. This makes development harder as it requires old versions of PHPUnit.
Installation of PHPUnit with composer does not work properly below PHP 5.5, so it requires some tweaks in .travis.yml to use the built-in PHPUnit from the Ubuntu image in these versions.
PHP 5.2 and 5.3 tests run on Ubuntu precise, which is EOL by Canonical.

I was implementing a new test, but discovered that the expectException call is not supported below PHPUnit 5.2.

I suggest the minimum requirement for this project should be raised to at least PHP 5.6.
The [oldest supported](https://www.php.net/supported-versions.php) PHP version is currently 7.2.

**Comment by ozh** [comment]
I dramatically concur.

**Comment by jrfnl** [comment]
The intention is to address this in version 2.0.0 - see #460
