### ISSUE TITLE
Switch to Travis-ci.com

### ISSUE THREAD

**Issue by jrfnl** [WordPress/Requests#420]
Travis is slowly closing down their old `.org` interface. I have seen a number of repos running into issues with Travis not reporting back on branches/pull requests anymore and sooner or later, this repo will be affected as well.

Based on my experiences with other repos, this is what needs to happen:

> How to get TravisCI working again if it's currently not reporting:
> 1. On GitHub/ repo Settings: Remove the Webhook integration.
> 2. On GitHub/ marketplace: Install the Travis GH App
> 3. On travis-ci.com: sign up for the migrations beta for the organisation
> 4. On travis-ci.com: migrate all relevant repos
> 5. For PRs without status: force push problem PRs (no change needed in the content of the PR)
> 6. Once a first build has finished under the new system, change the protected branches to require "Travis CI - Pull Request" and un-require "continuous integration"

Source: https://twitter.com/jrf_nl/status/1255854838597984262

As I don't have admin rights for this repo, I can't action this myself. @rmccue Would you please be so kind to action this ?

**Comment by jrfnl** [comment]
Let's put a pin in this for now. While travis.org is dreadfully slow at the moment, the .com interface is forcing paid plans since this week and the option for "free builds for Open Source" requires a request to be added to that plan, except they "forgotten" to build the interface to request this... *sigh*

Probably better to look at switching to GH actions in the near future.

**Comment by ozh** [comment]
My 2 cents : while switching to GH actions is certainly the sound thing to do, migrating to travis-ci.com litterally takes 15 seconds and works quite well (my experience these past 3 days at least). There's no reason to postpone, really.

**Comment by jrfnl** [comment]
@ozh Not in my experience. Did so on various projects and with the limited open source/free tokens, my builds would stop running by day three of the month, so Travis is no longer a viable options.

**Comment by ozh** [comment]
Well, not sure I still get it... Travis.org is 100% not working, Travis.com maybe working, so it's still better than nothing for a 15 seconds investment :)

**Comment by schlessera** [comment]
We're making good progress moving everything to GHA, so I'm closing this issue.
