### ISSUE TITLE
Hook priority not working

### ISSUE THREAD

**Issue by jegrandet** [WordPress/Requests#452]
Sorry in advance for my english

I use hook in order to change cURL options
As the bundle add its own hook, I add a priority nomber in order to run mine later.
Unfortunately, it hasn't changed anything.

After looking in the, I found the issue.
In the script of the hook, the priority is used as key for an array of hook.
However, even if the key is a number, the array is not sorted with it.

As solution, I propose to simply use ksort in the register function :
```php
public function register($hook, $callback, $priority = 0) {
	if (!isset($this->hooks[$hook])) {
		$this->hooks[$hook] = array();
	}
	if (!isset($this->hooks[$hook][$priority])) {
		$this->hooks[$hook][$priority] = array();
		ksort($this->hooks[$hook]);
	}
	$this->hooks[$hook][$priority][] = $callback;
}
```

**Comment by jrfnl** [comment]
Confirmed: https://3v4l.org/3TZNW Thanks for reporting this @jegrandet !

PR #647 should fix this. Testing appreciated.
