### ISSUE TITLE
Performance issue with "Expect" header and cURL

### ISSUE THREAD

**Issue by carlalexander** [WordPress/Requests#453]
By default, cURL adds a `Expect: 100-Continue` header to certain requests. This can add as much as a second delay to requests done using cURL. This is [discussed on the cURL mailing list](https://curl.se/mail/lib-2017-07/0013.html).

The general practice is to set an empty `Expect` header when the request payload is small. This is something other cURL clients like [Guzzle](https://github.com/guzzle/guzzle/blob/d5a2b0338e1cc963532ffdcc3bba4cbba469a215/src/RequestOptions.php#L96-L112) and [Stripe](https://github.com/stripe/stripe-php/blob/3febf22da8ed6a3b45842eac97d0fcece4d91e13/lib/HttpClient/CurlClient.php#L244-L256) do.

**Comment by carlalexander** [comment]
I've posted a [quick fix](https://gist.github.com/carlalexander/c779b473f62dcd1a4ca26fcaa637ec59) here for WordPress. But this should be in the cURL client ideally.

**Comment by schlessera** [comment]
Great find @carlalexander ! Are you up to providing a PR that only sends the `Expect: 100-continue` on requests with a body that's 1MB+ in size?

**Comment by carlalexander** [comment]
Yup, happy to do a PR @schlessera 😄
