### ISSUE TITLE
Tests configuration setup

### ISSUE THREAD

**Issue by jrfnl** [WordPress/Requests#459]
PR #457 contains a commit adding a test to the config.
This is the second time I've had to create a separate PR to add tests which were not automatically being run. Also see #366.

I'd like to propose removing the separate test suite configurations in favour of a generic setup which will automatically discover any new tests added to the `tests` directory.

The PHPUnit `--filter` CLI argument is powerful enough to handle selective running of the tests for most PHPUnit versions.

If needs be, for older PHPUnit versions, a `@group` annotation could be added to various tests to still allow them to be run in groups alike to the original testsuites.

**Comment by jrfnl** [comment]
Probably would be good to take this issue into account when setting up the namespaces for the tests for Requests 2.0.0. Also see #460.

**Comment by jrfnl** [comment]
To make this change, it would be best if all test classes are named as such.

Currently, the classes follow a pattern like: `RequestsTest_[SubDir_]_ClassName`.

For PHPUnit to be able to pick up on the tests automatically, the test classes should end on `Test` and for compatibility with PHPUnit 9.1.0+, the file names should match the class names, so, this ties in with the namespacing proposal in #460 and also PR #446 and should wait until the latter has been merged or a commit actioning this should be added to that PR.

Proposed naming conventions for the tests:
Namespace name | ClassName | FileName
--- | --- | ---
`Requests\Tests[\SubDir]` | `OriginalClassNameTest` | `OriginalClassNameTest.php`

This is in line with PSR4 and will allow for adding a `autoload-dev` section to the `composer.json` file to set up the autoloading of the tests. The custom autoload function can then be removed from the test bootstrap file.

Note: for dev setups using a PHPUnit phar file, we may need to test if the above is desirable or if this will inhibit testing against multiple PHP and PHPUnit versions via the Phar too much.
If that's the case, I would favour leaving the custom autoloader in the test bootstrap file in place.

Action list:
- [x] Add namespace statements to all files in the `tests` directory
- [x] Rename the test classes and files
- [x] Adjust the `phpunit.xml.dist` file to only declare one testsuite looking for all files ending on `Test.php`
- [x] MAYBE Add autoload-dev to `composer.json`
- [x] MAYBE Remove custom autoloader from bootstrap file in favour of loading the Composer `vendor/autoload.php` file.
    Alternatively, the custom autoloader should be adjusted to handle the new PSR4 based classname to filename translation.

**Comment by schlessera** [comment]
> Note: for dev setups using a PHPUnit phar file, we may need to test if the above is desirable or if this will inhibit testing against multiple PHP and PHPUnit versions via the Phar too much.
If that's the case, I would favour leaving the custom autoloader in the test bootstrap file in place.

I'm not entirely sure what issue you expect to arise here, but I've never had any problems as long as I add the Composer autoloader itself to the PHPUnit configuration's bootstrap section.

**Comment by jrfnl** [comment]
@schlessera And that's exactly the "secret" - If the Composer autoload file _is_ the bootstrap file (per the config or CLI args), there is no problem, however as soon as there is a _custom_ bootstrap file which _requires_ the Composer autoload file, you start running into signature mismatch problems if the `composer install` was run on a _high_ version of PHP and you are running the tests against a PHPUnit phar on a _low_ version of PHP.
