### ISSUE TITLE
Branching strategy

### ISSUE THREAD

**Issue by jrfnl** [WordPress/Requests#463]
As development has recently been more active than in the previous years, I'd like to discuss the branches used.

Currently, the repository uses one main branch, which is called `master`.

### Proposal

* Rename `master` to `main`.
* Add a `develop` branch and make that the default branch.
* Make both `main` as well as `develop` protected branches which require certain status checks to have passed.

### Proposed workflow

* The `main` branch would always contain the last release and should only receive a pull request when releasing a new version.
* The `develop` branch is where PRs are pulled to and where regular merges happen.

### Proposed timeline

* Enact the above once the `1.8.0` release has been tagged.

Opinions ?

**Comment by jrfnl** [comment]
Side-note for completeness: there is also an orphan `gh-pages` branch for the website, but that's not a branch used for regular development.

**Comment by TimothyBJacobs** [comment]
Shouldn't it be `trunk`? https://make.wordpress.org/core/2020/06/18/proposal-update-all-git-repositories-to-use-main-instead-of-master/

**Comment by jrfnl** [comment]
@TimothyBJacobs I'm not fussed about the name.

I do think this project can choose its own branch name though as it is a stand-alone project which is used far more widely than just in a WP context.

**Comment by schlessera** [comment]
If we go with both a development branch and a branch with the current latest release, I'd suggest naming the latter `stable` instead of `main`.

This way, going for the `stable` tag always gives you exactly that.

**Comment by jrfnl** [comment]
@schlessera Happy to use `stable`.

I use `stable` in my own repos as well for the exact same reason. Chose that before `main` became the "common" replacement name and before the change to `trunk` was announced.

**Comment by jrfnl** [comment]
Reminder for when this gets actioned:

- [x] Update CI badges to point to the new name for `master`.
- [x] Update download links and other references to branch names in README, CONTRIBUTING, docs and the GH Pages site.

**Comment by jrfnl** [comment]
PR #490 contains the in-repo changes needed as per the above comment.

The GH Pages branch will be (should be) updated on the next release.
